[tool.poetry]
name = "lab-assistant"
version = "0.1.0"
description = ""
authors = ["labar"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
langchain-core = "^0.3.12"
langchain = "^0.3.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
